### ISSUE TITLE
New surrendered village in undiscovered area stays undiscovered

### ISSUE THREAD

**Issue by BileDemon** [the3dfxdude/7kaa#264]
I played around with 7kaa for a little while and noticed a small problem early in the game.

My reputation was high enough for an independent village (in a different and still undiscovered part of the map) to surrender to my kingdom.
I wasn't able to see my new village on the minimap. The only way to find it was by clicking the notification message. Still I wasn't able to actually see the village, although it IS selectable when you know where to click in the dark.
Only when I called one of my villagers out of the village was the moment where the village and the area was discovered.

I don't know if this is already how the original game works, but shouldn't at least the village object itself be made visible when it already belongs to you? I think the red dot on the map should appear and the village should pop out of the dark area.

![7kaa1](https://user-images.githubusercontent.com/94478594/223364609-9e1dc70e-0cdd-44c6-95af-74cd4540cffe.jpg)

**Comment by the3dfxdude** [comment]
There are some issues with vision from the original version. I might have addressed similar things. This is probably unusual surrender code anyway. It should not be allowed to surrender someone that doesn't have vision on the town if it is independent. If you have an autosave that can reproduce it, send it over.

**Comment by BileDemon** [comment]
Unfortunately no autosave, they tend to get overwritten pretty quickly and my main savegame is very far ahead of when this thing occurred.

But now that you say it, it really makes sense that there should not be any diplomatic communication between factions that have not even discovered each other.

**Comment by the3dfxdude** [comment]
It was a kingdom that surrendered to you. I see no other possibility of an independent town or individual kingdom town due to built in game rules.
Fixed with 52b1f9481413841e7e155dd7a874fa055e1b7695

**Comment by BileDemon** [comment]
Thank you for fixing this. And I'm really glad that the game still gets improvements.

As for your explanation, that this must have been a kingdom that surrendered to me:
I stated above that the only way to "find" my new village was by clicking the notification message that was still shown at the bottom of the screen. This action then centered the view on the village and also selected the village (? not sure about this).
Let's assume for a moment, that it was actually a message that said "XY's kingdom has surrendered to you", then it would not center the view on a single village, would it?
I think I do remember that it was rather a message of the type "independent village of XY surrendered to you", where the view is centered on top of the village directly. I don't think that the little bullet point had any kingdom color.

But on the other hand, when you say that there is no way for this to happen with an independent village, then I'm probably wrong about this.

**Comment by the3dfxdude** [comment]
Since this was never caught in testing, the messages if they could even happen, probably don't make sense as you say. Many messages and responses do hinge on your contact status. But since it is plugged, no reason to chase it down.

Individual villages can only choose to change their flag to kingdoms that have buildings connected. It is probably the fundamental rule of the entire game. So I didn't see any other way given the description.
